name: Build Releases

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always
  BIN_NAME: graph-explorer

# Yes I'm aware this doesn't work and only produces windows binaries
# No I don't care enough to fix it right now.
jobs:
  release:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: cargo build --release

      - name: Rename binary (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          mv target/release/$BIN_NAME \
             $BIN_NAME-linux-x86_64

      - name: Upload binary (Linux)
        if: matrix.os == 'ubuntu-latest'
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ env.BIN_NAME }}-linux-x86_64

      
      - name: Rename binary (Windows)
        if: matrix.os == 'windows-latest'
        shell: pwsh
        run: |
          mv target/release/$env:BIN_NAME.exe `
             $env:BIN_NAME-windows-x86_64.exe
      
      - name: Upload binary (Windows)
        if: matrix.os == 'windows-latest'
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ env.BIN_NAME }}-windows-x86_64.exe
